# Generated by Django 5.2.8 on 2026-05-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intents_api', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='day_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
